services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST:-host.docker.internal}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DB_POOL_SIZE: ${DB_POOL_SIZE:-5}
      DB_MAX_OVERFLOW: ${DB_MAX_OVERFLOW:-10}
      DB_POOL_RECYCLE: ${DB_POOL_RECYCLE:-1800}
      SQLALCHEMY_ECHO: ${SQLALCHEMY_ECHO:-false}
    ports:
      - "8501:8501"
    volumes:
      - ./:/app